config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :topics do
    resources :bookmarks, except: [:index, :show], controller: 'topics/bookmarks' do
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :users, only: [:show]


  get 'welcome/about'

  post 'incoming', to: 'incoming#create'

  root to: 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  before_create :http_url

  private

    def http_url
      if self.url[0..6] != 'http://' || self.url[0..7] != 'https://'
        self.url = self.url.prepend('http://')
      end
    end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy

  def to_param
    "#{id} #{title}".parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :topics
  has_many :bookmarks
  has_many :likes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def to_param
    "#{id} #{email.split('@').first}".parameterize
  end

  def admin?
    role == 'admin'
  end

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception


  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: "You aren't allowed to access that page."
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
#  def show
#    @bookmark = Bookmark.find(params[:id])
#  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

    def create
      @topic = Topic.find(params[:topic_id])
      @bookmark = Bookmark.new(params.require(:bookmark).permit(:url, :topic_id))
      @bookmark.topic = @topic

      if @bookmark.save
        redirect_to @topic, notice: "New bookmark saved"
      else
        flash[:error] = "There was a problem saving your bookmark. Please try again!"
        redirect_to @topic
      end
    end


  def edit
    @bookmark = Bookmark.find(params[:id])
  end

    def update
      @bookmark = Bookmark.find(params[:id])

      if @bookmark.update_attributes(params.require(:bookmark).permit(:url))
        redirect_to @bookmark.topic, notice: "Bookmark successfully edited"
      else
        flash[:error] = "There was a problem editing your bookmark. Please try again!"
        render :edit
      end
    end

    def destroy
      @topic = Topic.find(params[:topic_id])
      @bookmark = Bookmark.find(params[:id])

      if @bookmark.destroy
        flash[:notice] = "Bookmark has been deleted"
        redirect_to @topic
      else
        flash[:error] = "There was a problem deleting your bookmark. Please try again!"
        redirect_to @topic
      end
    end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    puts "INCOMING PARAMS: #{params}"

    @user = User.where(email: params[:sender])
    @topic = Topic.where(title: params[:subject])
    url = params["body-plain"]

    if @user.blank?
      name = params[:sender].split("@").first
      user = User.new(name: name, email: params[:sender], password: "password")
      user.save!
    end

    if @topic.blank?
      topic = Topic.new(title: params[:subject], user_id: user)
      topic.save!
    end

    bookmark = Bookmark.create(topic_id: topic.id, url: url)

    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    authorize @like

    if @like.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.find(params[:id])
    authorize @like

    if @like.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end
end

app/controllers/topics/bookmarks_controller.rb
class Topics::BookmarksController < ApplicationController

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

    def create
      @topic = Topic.find(params[:topic_id])
      @bookmark = current_user.bookmarks.build(params.require(:bookmark).permit(:url, :topic_id))
      @bookmark.topic = @topic
      authorize @bookmark

      if @bookmark.save
        redirect_to @topic, notice: "New bookmark saved"
      else
        flash[:error] = "There was a problem saving your bookmark. Please try again!"
        redirect_to @topic
      end
    end


  def edit
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

    def update
      @bookmark = Bookmark.find(params[:id])
      authorize @bookmark

      if @bookmark.update_attributes(params.require(:bookmark).permit(:url))
        redirect_to @bookmark.topic, notice: "Bookmark successfully edited"
      else
        flash[:error] = "There was a problem editing your bookmark. Please try again!"
        render :edit
      end
    end

    def destroy
      @topic = Topic.find(params[:topic_id])
      @bookmark = Bookmark.find(params[:id])
      authorize @bookmark

      if @bookmark.destroy
        flash[:notice] = "Bookmark has been deleted"
        redirect_to @topic
      else
        flash[:error] = "There was a problem deleting your bookmark. Please try again!"
        redirect_to @topic
      end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.joins(:bookmarks).uniq # May want to make this more user-friendly... How would one create a topic, which is then empty, and then add a bookmark to it if they left the topic's #show page?
  end

  def show
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

    def create
      @topic = current_user.topics.build(params.require(:topic).permit(:title))
      authorize @topic

      if @topic.save
        redirect_to @topic, notice: "New topic saved"
      else
        flash[:error] = "There was a problem saving your post. Please try again!"
        redirect_to topics_path
      end
    end

    def update
      @topic = Topic.find(params[:id])
      authorize @topic

      if @topic.update_attributes(params.require(:topic).permit(:title))
        redirect_to @topic
      else
        flash[:error] = "There was a problem updating #{@topic.title}"
        render :edit
      end
    end

    def destroy
      @topic = Topic.find(params[:id])
      authorize @topic

      if @topic.destroy
        flash[:notice] = "#{@topic.title} has been deleted"
        redirect_to topics_path
      else
        flash[:error] = "There was a problem deleting the topic. Please try again!"
        render :show
      end
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :get_bookmark

  def show
    @user = User.find(params[:id])
    @user_bookmarks = @user.bookmarks
    @liked_bookmarks = Bookmark.joins(:likes).where(likes: { user_id: @user.id })
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
require 'embedly'
require 'json'

module BookmarksHelper

  def embed(url)
    embedly_api = Embedly::API.new :key => ENV['EMBEDLY_API']
    obj = embedly_api.oembed :url => url
    return obj[0].marshal_dump
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title= Markit
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    = stylesheet_link_tag 'application', media:'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    - if flash[:error]
      .alert.alert-danger= flash[:error]
    - if flash[:alert]
      .alert.alert-warning= flash[:alert]
    - if flash[:notice]
      .alert.alert-success= flash[:notice]

    %nav.navbar
      .container
        %ul.nav.nav-tabs
          %li= link_to "Home", root_url
          %li= link_to "Topics", topics_path
          %li= link_to "About", welcome_about_path
          - if current_user
            %li.navbar-right= link_to "Sign Out", destroy_user_session_path, method: :delete
            %li.navbar-right= link_to "Profile", current_user
          -else
            %li.navbar-right= link_to "Sign Up", new_user_registration_path
            %li.navbar-right= link_to "Log In", new_user_session_path

    .container
      = yield

app/views/likes/_like.html.haml
%div
  - if like = current_user.liked(bookmark)
    = link_to [bookmark.topic, bookmark, like], class: 'btn btn-primary favorite', method: :delete do
      %i.glyphicon.glyphicon-star-empty
  - else
    = link_to [bookmark.topic, bookmark, Like.new], class: 'btn btn-default favorite', method: :post do
      %i.glyphicon.glyphicon-star

app/views/likes/_liked_bookmarks.html.haml
- record.each do |like|
  .col-md-3.bookmark-loop
    .bookmark-box
      = like.url
      - if policy(like).edit?
        .small
          = link_to "Edit Bookmark", edit_topic_bookmark_path(like.topic, like)
      - if policy(like).destroy?
        .small
          = link_to "Delete Bookmark", [like.topic, like], method: :delete
      - if policy(Like.new).create?
        = render partial: 'likes/like', locals: { bookmark: like }

app/views/topics/_bookmarks.html.haml
- record.bookmarks.each do |bookmark|
  - bookmark_title = bookmark.url.split('.')[1]
  .col-md-3.bookmark-loop
    .bookmark-box
      = link_to "#{bookmark.url}" do
        %h4
          = bookmark_title
      = embed(bookmark.url)[:description].truncate(90)
      - if policy(Like.new).create?
        = render partial: 'likes/like', locals: { bookmark: bookmark }
      - if policy(bookmark).edit?
        .small
          = link_to "Edit Bookmark", edit_topic_bookmark_path(bookmark.topic, bookmark)
        .small
          = link_to "Delete Bookmark", [bookmark.topic, bookmark], method: :delete

app/views/topics/bookmarks/edit.html.haml
%h1 Edit Bookmark

.col-md-8
  = form_for [@bookmark.topic, @bookmark] do |f|
    .form-group
      = f.label :url
      = f.text_field :url, class: 'form-control', placeholder: "#{@bookmark.url}"
    .form-group
      = f.submit 'Save', class: 'btn btn-success'
      = link_to "Delete Bookmark", [@bookmark.topic, @bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this bookmark?" }
.col-md-4

app/views/topics/bookmarks/new.html.haml
%h1 New Bookmark

.col-md-8
  = form_for [@topic, @bookmark] do |f|
    .form-group
      = f.label :url
      = f.text_field :url, class: 'form-control', placeholder: "Bookmark URL"
    .form-group
      = f.submit "Save", class: 'btn btn-success'
.col-md-4

app/views/topics/edit.html.haml
%h1 Edit #{@topic.title}

.col-md-8
  = form_for @topic do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: "form-control", placeholder: "#{@topic.title}"
    .form-group
      = f.submit "Save", class: "btn btn-success"
      = link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete #{@topic.title}?" }
.col-md-4

app/views/topics/index.html.haml
%h1 Topics

- if policy(@topics).new?
  %button.btn.btn-success
    = link_to "New Topic", new_topic_path

.row
  - @topics.each do |topic|
    - if topic.bookmarks.length > 0
      .col-md-12
        %h3
          = link_to "##{topic.title}", topic
        = render partial: "bookmarks", locals: { record: topic }

app/views/topics/new.html.haml
%h1 New Topic

.col-md-8
  = form_for @topic do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control', placeholder: "Topic Name"
    .form-group
      = f.submit "Save", class: 'btn btn-success'
.col-md-4

app/views/topics/show.html.haml
%h1 #{@topic.title}
- if policy(@topic).edit?
  %button.btn.btn-primary
    = link_to "Edit Topic", edit_topic_path(@topic)
  %button.btn.btn-danger
    = link_to "Delete Topic", @topic, method: :delete
- if policy(@topic.bookmarks).new?
  %button.btn.btn-success
    = link_to "New Bookmark", new_topic_bookmark_path(@topic)

.row-buffer

.col-md-12
  .media-body
    = render partial: 'bookmarks', locals: { record: @topic }

app/views/users/show.html.haml
%h1 #{@user.name || @user.email}'s Profile
%a= link_to "Profile Settings", edit_user_registration_path

.col-md-12
  %h2 Bookmarks
  .media-body
    = render partial: 'topics/bookmarks', locals: { record: @user }
.col-md-12
  %h2 Favorites
  .media-body
    = render partial: 'likes/liked_bookmarks', locals: { record: @liked_bookmarks }

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>